language: go

go:
- 1.16.x
- master

env:
  global: 
  - GOOGLE_PROJECT_ID=test
  - FIRESTORE_EMULATOR_HOST=localhost:8080

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: go test .
    - name: "Integration Tests"
      before_script: curl -sL https://firebase.tools | bash
      script: firebase emulators:exec './run_integration_test.sh'